---
title: "Data Manipulation"
output: github_document
---


```{r Set-up}
library(tidyverse)
```

## Load the FAS_litters data 

```{r}
litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```
## `select`

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```
Alternatively:

```{r}
select(litters_data, group:gd_of_birth)
```

Removing:

```{r}
select(litters_data, -pups_survive)
```

Renaming variables

```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```
Alternatively

```{r}
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
select(litters_data, starts_with("gd"))
```

```{r}
select(litters_data, litter_number, pups_survive, everything())
```

## Filter 

```{r}
filter(pups_data, sex == 1)
```

```{r}
filter(pups_data, sex == 2, pd_walk < 11)
```


Doing the same with FAS_pups

```{r}
select(pups_data, litter_number, sex, pd_ears)
```

## Mutate 

```{r}
mutate(
  litters_data, 
  group = str_to_lower(group),
  wt_gain = gd18_weight - gd0_weight)
```

```{r}
mutate(
  pups_data, 
  new_pd_pivot = pd_pivot - 7,
  sum_pd = pd_ears + pd_eyes + pd_pivot + pd_walk
  )
```


## Arrange

```{r}
arrange(litters_data, group, pups_born_alive)
```

