---
title: "Data Import"
output: github_document
---


```{r Set-up}
library(tidyverse)
library(readxl)
library(haven)
```
## Read in some data

Read in the litters dataset.

```{r Importing and storing data}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

## Take a look at the data

Printing in the console

```{r}
litters_data
```

```{r}
tail(litters_data)
```

```{r}
skimr::skim(litters_data)
```

### Options to read_csv

```{r}
litters_data = read_csv("./data/FAS_litters.csv", na = c("", "NA", 9999, "."))
```
Check out `?read_csv` for more information. 

## Other file formats 

Read in an excel file.

```{r}
mlb_df = read_excel("./data/mlb11.xlsx")
mlb_df
```

Read in a SAS file.

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df = janitor::clean_names(pulse_df)
pulse_df
```

## Comparison with Base R

What about `read.csv`...?

```{r}
litters_base = read.csv(file = "./data/FAS_litters.csv")
litters_readr = read_csv(file = "./data/FAS_litters.csv")

litters_base
litters_readr
```

## Exporting data 

Export the mlb 

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```

